version: '3.5'
services:
  rest-api:
    build:
      context: ./backend/
      dockerfile: dockerfile
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
      - REACT_APP_API_URL=http://localhost:3000/api
    ports:
      - 3000:80
    environment:
      - NODE_ENVIRONMENT=production
    depends_on:
      - rest-api

volumes:
  db:
    driver: local
