name: Deploy demo

on:
  push:
    branches:
      - demo
    paths:
      - backend/**


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: inventum
          dockerfile_directory: ./backend
          dockerfile_name: dockerfile.heroku
          process_type: web
          
