name: Deploy demo

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Build Docker image
      - name: Docker build
        run: docker login --password=$HEROKU_API_KEY registry.heroku.com

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push web -a inventum
          heroku container:release web -a inventum
        working-directory: ./backend
